'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, Bot, BrainCircuit, ChevronRight, CircleDot, CloudRain, Command, Cpu, Crosshair, Gauge, LayoutDashboard, Map, Menu, Mic, ParkingCircle, Plane, Play, Radio, Route, ShieldAlert, Sparkles, Users, Utensils, Wind } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';

const agents = [
  ['Crowd AI','98.4','Managing flow vectors','cyan'], ['Navigation AI','96.8','Rerouting arrivals','blue'], ['Security AI','99.1','Perimeter nominal','violet'], ['Emergency AI','97.5','Standby protocol','amber'], ['Food AI','94.3','Demand forecast sync','pink'], ['Energy AI','99.6','Load optimized','green']
];
const pages = [['Command Center',LayoutDashboard],['Digital Twin',Map],['Scenario Lab',Sparkles],['AI Negotiation',BrainCircuit],['Agent Network',Bot],['Predictive Analytics',Gauge],['Emergency Center',ShieldAlert],['Crowd Control',Users],['Tournament Manager',Crosshair],['Volunteer Center',Users],['Drone Fleet',Plane],['Parking',ParkingCircle],['Economy',Activity],['Accessibility',CircleDot],['Sustainability',Wind],['Reports',Activity],['Settings',Cpu]];
const chart = [{t:'14:00',v:51},{t:'14:15',v:55},{t:'14:30',v:62},{t:'14:45',v:69},{t:'15:00',v:74},{t:'15:15',v:72},{t:'15:30',v:81}];
const scenarios = [
  { name:'Heavy Rain', icon:CloudRain, impact:'High', cascade:['Parking delay +18 min','Late arrivals at gates','East concourse density +24%','Food demand shifts indoors'], color:'#61b6ff' },
  { name:'Medical Emergency', icon:AlertTriangle, impact:'Critical', cascade:['Dispatch drone AED','Open medical corridor','Volunteer team mobilized','Navigation isolates sector'] , color:'#ff8674'},
  { name:'Gate Closure', icon:Route, impact:'High', cascade:['Redistribute 8,600 visitors','Queue capacity rebalanced','Shuttle route updated','Security perimeter adapted'], color:'#b89bff'},
  { name:'Attendance +50%', icon:Users, impact:'High', cascade:['Staffing need +42','Parking overflow predicted','Energy peak rescheduled','Food stock transfer'], color:'#42e8c8'}
];

export default function CommandCenter() {
  const [section,setSection] = useState('Command Center'); const [time,setTime] = useState(0); const [scenario,setScenario] = useState<typeof scenarios[0] | null>(null); const [command,setCommand] = useState(''); const [open,setOpen]=useState(true);
  useEffect(()=>{ const x=setInterval(()=>setTime(v=>(v+1)%100),1800); return()=>clearInterval(x); },[]);
  const total = 64328 + time * 7;
  function run(s: typeof scenarios[0]) { setScenario(s); setSection('Scenario Lab'); }
  return <main className="min-h-screen relative flex">
    <aside className="w-[245px] shrink-0 border-r border-blue-200/10 bg-[#070d1d]/85 p-5 hidden lg:flex flex-col z-10">
      <div className="flex items-center gap-3 mb-10"><div className="w-9 h-9 rounded-xl bg-gradient-to-br from-cyan-300 to-blue-600 grid place-items-center glow"><Command size={19}/></div><div><div className="font-bold tracking-tight">STADIUM<span className="text-cyan-300">OS</span></div><div className="text-[9px] tracking-[.24em] text-slate-500">AI X / COMMAND</div></div></div>
      <nav className="space-y-1">{pages.map(([name,Icon])=><button key={name as string} onClick={()=>setSection(name as string)} className={`w-full flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${section===name?'bg-blue-500/15 text-cyan-200 border border-blue-300/15':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon size={16}/>{name as string}{section===name&&<ChevronRight size={14} className="ml-auto"/>}</button>)}</nav>
      <div className="mt-auto panel p-3"><div className="flex justify-between eyebrow"><span>System health</span><span className="text-emerald-300">99.92%</span></div><div className="h-1.5 rounded-full bg-slate-800 mt-3"><div className="h-full w-[99%] rounded-full bg-gradient-to-r from-cyan-400 to-emerald-300"/></div><p className="text-[10px] text-slate-500 mt-2">16 autonomous agents online</p></div>
    </aside>
    <div className="flex-1 min-w-0 p-4 md:p-7 relative z-10">
      <header className="flex items-center justify-between gap-4 mb-6"><div className="flex items-center gap-3 lg:hidden"><Menu/><span className="font-semibold">STADIUMOS</span></div><div className="hidden lg:block"><div className="eyebrow">Olympic city · match day 04</div><h1 className="text-xl font-semibold mt-1">{section}</h1></div><div className="flex items-center gap-3"><div className="hidden md:flex items-center gap-2 panel px-3 py-2 text-xs text-slate-400"><Radio size={13} className="text-emerald-300 pulse"/> LIVE SIMULATION · 15:32:18</div><button onClick={()=>setOpen(!open)} className="panel p-2 text-cyan-200"><Mic size={17}/></button><div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-cyan-300 border border-white/30"/></div></header>
      {open && <div className="mb-5 panel px-4 py-3 flex gap-3 items-center"><Mic size={16} className="text-cyan-300"/><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run(scenarios.find(x=>command.toLowerCase().includes(x.name.toLowerCase().split(' ')[0]))||scenarios[0])} placeholder='Command the operating system…  e.g. “simulate heavy rain”' className="bg-transparent outline-none text-sm flex-1 placeholder:text-slate-600"/><span className="text-[10px] text-slate-500 hidden md:block">VOICE ENABLED</span></div>}
      {section==='Command Center' ? <Dashboard total={total} run={run}/> : section==='Scenario Lab' ? <Scenario scenario={scenario} run={run}/> : section==='AI Negotiation' ? <Negotiation/> : <Operations title={section} time={time}/>} 
    </div>
  </main>
}

function Dashboard({total,run}:{total:number,run:(s:typeof scenarios[0])=>void}) { return <><div className="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-4">{[['Live attendance',total.toLocaleString(),'82.1% capacity',Users],['Flow efficiency','94.7%','↑ 3.2% optimal',Route],['Open incidents','03','1 needs attention',AlertTriangle],['Energy draw','4.28 MW','−11% vs baseline',Wind]].map(([a,b,c,I])=>{const Icon=I as typeof Users; return <div className="panel p-4" key={a as string}><div className="flex justify-between eyebrow"><span>{a as string}</span><Icon size={14} className="text-cyan-300"/></div><div className="metric mt-3">{b as string}</div><div className="text-[11px] text-emerald-300 mt-1">{c as string}</div></div>})}</div><div className="grid xl:grid-cols-[1.5fr_.85fr] gap-4"><Twin/><div className="space-y-4"><LiveFeed/><AgentGrid/></div></div><div className="grid xl:grid-cols-[1.25fr_.75fr] gap-4 mt-4"><div className="panel p-5"><div className="flex justify-between"><div><div className="eyebrow">Predictive intelligence</div><h2 className="font-semibold mt-1">Concourse density forecast</h2></div><span className="text-xs text-cyan-200">NEXT 90 MIN</span></div><div className="h-40 mt-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="a" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#42e8c8" stopOpacity=".55"/><stop offset="1" stopColor="#42e8c8" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="t" axisLine={false} tickLine={false} tick={{fill:'#71809d',fontSize:10}}/><Tooltip/><Area type="monotone" dataKey="v" stroke="#42e8c8" fill="url(#a)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="panel p-5"><div className="eyebrow">Run a scenario</div><div className="mt-3 grid grid-cols-2 gap-2">{scenarios.map(s=>{const ScenarioIcon=s.icon; return <button onClick={()=>run(s)} className="text-left rounded-xl bg-white/[.04] hover:bg-white/[.08] p-3 transition" key={s.name}><ScenarioIcon size={16} style={{color:s.color}}/><div className="text-xs mt-2">{s.name}</div></button>})}</div></div></div></> }

function Twin() { const dots=useMemo(()=>Array.from({length:55},(_,i)=>({x:(i*37)%88+6,y:(i*61)%74+13})),[]); return <section className="panel min-h-[460px] overflow-hidden relative p-5"><div className="relative z-10 flex justify-between"><div><div className="eyebrow">Live digital twin / venue 01</div><h2 className="font-semibold mt-1">Aurelia National Stadium</h2></div><div className="flex gap-2 text-[10px]"><span className="rounded-full px-2 py-1 bg-emerald-400/10 text-emerald-300">● SYNCHRONIZED</span><span className="rounded-full px-2 py-1 bg-blue-400/10 text-blue-200">3D ACTIVE</span></div></div><div className="absolute inset-x-7 top-20 bottom-8 rounded-[46%] border-[20px] border-slate-300/10 bg-[radial-gradient(ellipse_at_center,rgba(17,118,129,.34),rgba(5,11,28,.1)_48%,transparent_49%)] shadow-[inset_0_0_60px_rgba(55,169,255,.15)]"><div className="absolute inset-[14%] rounded-[48%] border border-cyan-200/30 bg-[#112d3c]"><div className="absolute inset-[24%] rounded-[46%] border border-cyan-100/25 bg-[#084752] shadow-[0_0_40px_rgba(42,232,200,.28)]"/><div className="absolute inset-[41%] rounded-[40%] bg-[#192c46] border border-white/20"/></div>{dots.map((d,i)=><i key={i} className={`absolute w-1.5 h-1.5 rounded-full ${i%7===0?'bg-amber-300 pulse':'bg-cyan-200/80'}`} style={{left:`${d.x}%`,top:`${d.y}%`,animationDelay:`${i%4*.3}s`}}/>)}<div className="absolute left-[15%] top-[38%] text-[9px] text-cyan-100/80">NORTH GATE · 82%</div><div className="absolute right-[12%] bottom-[27%] text-[9px] text-amber-200">QUEUE · 7 MIN</div></div><div className="absolute bottom-5 left-5 flex gap-2 text-[10px] text-slate-300"><span className="panel px-2 py-1.5">64,328 VISITORS</span><span className="panel px-2 py-1.5">12 DRONES</span><span className="panel px-2 py-1.5">WEATHER: CLEAR</span></div></section> }
function LiveFeed(){return <section className="panel p-4"><div className="flex justify-between"><div className="eyebrow">Autonomous activity</div><span className="text-[10px] text-cyan-300">LIVE FEED</span></div><div className="mt-3 space-y-3">{[['15:32:18','Navigation AI','Optimized East concourse route','cyan'],['15:31:56','Food AI','Shifted inventory to Zone C','pink'],['15:31:22','Security AI','Patrol 04 rebalanced','violet']].map(x=><div key={x[0]} className="flex gap-3 text-xs"><span className="text-slate-600 font-mono text-[10px]">{x[0]}</span><span className="w-1.5 h-1.5 mt-1 rounded-full bg-cyan-300"/><div><b className="font-medium text-slate-200">{x[1]}</b><p className="text-slate-500 mt-0.5">{x[2]}</p></div></div>)}</div></section>}
function AgentGrid(){return <section className="grid grid-cols-2 gap-2">{agents.slice(0,4).map(a=><div key={a[0]} className="panel p-3"><div className="flex justify-between text-[11px]"><span>{a[0]}</span><CircleDot size={13} className="text-emerald-300"/></div><div className="text-lg font-bold mt-1">{a[1]}<small className="text-[9px] text-slate-500">% confidence</small></div><div className="text-[9px] text-slate-500 mt-1">{a[2]}</div></div>)}</section>}
function Scenario({scenario,run}:{scenario:typeof scenarios[0]|null,run:(s:typeof scenarios[0])=>void}){const ActiveIcon=scenario?.icon; return <div className="grid xl:grid-cols-[.7fr_1.3fr] gap-4"><section className="panel p-5"><div className="eyebrow">Scenario library</div><h2 className="mt-1 font-semibold">Stress-test your venue</h2><div className="space-y-2 mt-5">{scenarios.map(s=>{const ScenarioIcon=s.icon; return <button key={s.name} onClick={()=>run(s)} className={`w-full text-left p-3 rounded-xl border ${scenario?.name===s.name?'bg-cyan-400/10 border-cyan-300/35':'bg-white/[.025] border-white/5 hover:bg-white/[.06]'}`}><div className="flex items-center gap-3"><ScenarioIcon size={18} style={{color:s.color}}/><span className="text-sm">{s.name}</span><span className="ml-auto text-[9px] text-slate-500">{s.impact}</span></div></button>})}</div></section><section className="panel p-6">{scenario&&ActiveIcon?<><div className="flex items-center gap-3"><ActiveIcon size={24} style={{color:scenario.color}}/><div><div className="eyebrow">Simulation executing</div><h2 className="font-semibold text-xl">{scenario.name}</h2></div><button className="ml-auto rounded-lg bg-cyan-300 text-slate-950 px-3 py-2 text-xs font-bold flex gap-1 items-center"><Play size={13}/> REPLAY</button></div><div className="mt-7 relative">{scenario.cascade.map((c,i)=><div className="flex gap-4 relative" key={c}><div className="w-8 flex flex-col items-center"><span className="w-7 h-7 rounded-full bg-cyan-400/15 border border-cyan-300/50 grid place-items-center text-xs text-cyan-200">{i+1}</span>{i<3&&<span className="w-px h-10 bg-cyan-300/30"/>}</div><div className="pt-1"><div className="text-sm">{c}</div><div className="text-[11px] text-slate-500 mt-1">Agent response synchronized · confidence {98-i}%</div></div></div>)}</div><div className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-400/[.06] p-4"><div className="eyebrow text-emerald-300">Master decision AI</div><p className="text-sm mt-2">Deploy volunteers to East Concourse, preserve Gate A capacity, and activate predictive wayfinding. Expected outcome: visitor flow stable within 11 minutes.</p></div></>:<div className="h-full min-h-96 grid place-items-center text-center"><Sparkles size={32} className="text-cyan-300"/><div><h2 className="font-semibold mt-3">Choose a scenario to begin</h2><p className="text-sm text-slate-500 mt-2">Every simulated event triggers a multi-agent cascade.</p></div></div>}</section></div>}
function Negotiation(){return <section className="panel p-6 max-w-5xl"><div className="eyebrow">Agent negotiation engine · decision #A-2041</div><h2 className="font-semibold text-xl mt-1">East gate congestion strategy</h2><div className="mt-6 grid md:grid-cols-3 gap-3">{[['Crowd AI','Close Gate A to reduce pressure','PROPOSED','#55dfdf'],['Navigation AI','Reject: traffic rises 26%','COUNTER','#9e8cff'],['Emergency AI','Keep open; deploy volunteers','SUPPORTED','#ffbf70']].map(x=><div className="rounded-xl border border-white/10 p-4 bg-white/[.03]" key={x[0]}><div className="flex justify-between text-xs"><b>{x[0]}</b><span style={{color:x[3]}}>{x[2]}</span></div><p className="text-sm text-slate-300 mt-5">{x[1]}</p><div className="mt-4 h-1 rounded bg-slate-800"><div className="h-full rounded bg-cyan-300" style={{width:'84%'}}/></div></div>)}</div><div className="my-5 flex justify-center"><ChevronRight className="rotate-90 text-cyan-300"/></div><div className="rounded-xl bg-gradient-to-r from-cyan-400/15 to-indigo-400/10 border border-cyan-200/20 p-5"><div className="flex items-center gap-2"><Cpu size={18} className="text-cyan-300"/><b>Master Decision AI · consensus reached</b><span className="ml-auto text-emerald-300 text-xs">96.8% confidence</span></div><p className="mt-3 text-sm text-slate-300">Keep Gate A open. Deploy 10 volunteers, redirect 14% of incoming visitors through Gate C, and introduce a temporary security lane. No emergency-access tradeoff.</p></div></section>}
function Operations({title,time}:{title:string,time:number}){const config:Record<string,string>={'Emergency Center':'Medical readiness and incident choreography','Crowd Control':'Density, flow vectors, and queue interventions','Drone Fleet':'Autonomous aerial monitoring and response','Parking':'Mobility orchestration across 12,400 bays','Economy':'Real-time event value and concession intelligence'};return <><div className="panel p-6"><div className="eyebrow">Operational intelligence</div><h2 className="text-2xl font-semibold mt-1">{config[title]||`${title} operations`}</h2><p className="text-sm text-slate-500 mt-2">Autonomous agents are continuously predicting, negotiating, and optimizing conditions across the venue.</p><div className="grid sm:grid-cols-3 gap-3 mt-6">{[['Signal integrity','99.92%'],['Predicted risk','LOW'],['Active automations',String(18+time%8)]].map(x=><div className="rounded-xl bg-white/[.04] border border-white/5 p-4" key={x[0]}><div className="eyebrow">{x[0]}</div><div className="metric mt-3">{x[1]}</div></div>)}</div></div><div className="mt-4 grid md:grid-cols-2 gap-4"><Twin/><section className="panel p-5"><div className="eyebrow">Agent directive timeline</div>{agents.map((a,i)=><div className="py-4 border-b border-white/5 last:border-0 flex gap-3" key={a[0]}><div className="w-2 h-2 rounded-full bg-cyan-300 mt-1.5"/><div><b className="text-sm">{a[0]}</b><p className="text-xs text-slate-500 mt-1">{a[2]} · confidence {a[1]}%</p></div><span className="ml-auto text-[10px] text-slate-600">{i+1}m ago</span></div>)}</section></div></>}
